"""粉丝表

Revision ID: 6b537165188f
Revises: 43133f51cf3e
Create Date: 2019-06-06 16:29:45.341077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b537165188f'
down_revision = '43133f51cf3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_fans',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followered_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['followered_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followered_id')
    )
    op.create_table('news_like',
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('news_id', 'user_id')
    )
    op.create_table('comment_like',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('comment_id', 'user_id')
    )
    op.drop_constraint('user_collection_ibfk_1', 'user_collection', type_='foreignkey')
    op.create_foreign_key(None, 'user_collection', 'news', ['collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_collection', type_='foreignkey')
    op.create_foreign_key('user_collection_ibfk_1', 'user_collection', 'user', ['collection_id'], ['id'])
    op.drop_table('comment_like')
    op.drop_table('news_like')
    op.drop_table('user_fans')
    # ### end Alembic commands ###
