"""user模型类迁移

Revision ID: 78f17c2f2a0d
Revises: 602cf3f8a7c2
Create Date: 2019-06-03 23:22:18.494436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78f17c2f2a0d'
down_revision = '602cf3f8a7c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('mobile', sa.String(length=11), nullable=True))
    op.add_column('user', sa.Column('nick_name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('signature', sa.String(length=255), nullable=True))
    op.drop_index('email', table_name='user')
    op.drop_index('face', table_name='user')
    op.drop_index('ix_user_addtime', table_name='user')
    op.drop_index('name', table_name='user')
    op.drop_index('phone', table_name='user')
    op.drop_index('uuid', table_name='user')
    op.create_unique_constraint(None, 'user', ['mobile'])
    op.create_unique_constraint(None, 'user', ['nick_name'])
    op.drop_column('user', 'face')
    op.drop_column('user', 'addtime')
    op.drop_column('user', 'email')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'pwd')
    op.drop_column('user', 'uuid')
    op.drop_column('user', 'name')
    op.drop_column('user', 'info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('info', mysql.TEXT(), nullable=True))
    op.add_column('user', sa.Column('name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('user', sa.Column('uuid', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('pwd', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('user', sa.Column('phone', mysql.VARCHAR(length=11), nullable=True))
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('user', sa.Column('addtime', mysql.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('face', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('uuid', 'user', ['uuid'], unique=True)
    op.create_index('phone', 'user', ['phone'], unique=True)
    op.create_index('name', 'user', ['name'], unique=True)
    op.create_index('ix_user_addtime', 'user', ['addtime'], unique=False)
    op.create_index('face', 'user', ['face'], unique=True)
    op.create_index('email', 'user', ['email'], unique=True)
    op.drop_column('user', 'signature')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'nick_name')
    op.drop_column('user', 'mobile')
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'avatar_url')
    # ### end Alembic commands ###
